# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openeats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='author',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
