# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default='Tell everyone something about yourself', verbose_name='about')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='None', help_text='What are ya?', max_length=5, null=True, verbose_name='gender')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('location', models.CharField(blank=True, default='', max_length=150, verbose_name='location')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'User profiles',
            },
        ),
    ]
